apiVersion: apps/v1
kind: Deployment
metadata:
  name: SimpleOrderHome
  labels:
    app: SimpleOrderHome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SimpleOrderHome
  template:
    metadata:
      labels:
        app: SimpleOrderHome
    spec:
      containers:
        - name: SimpleOrderHome
          image: username/SimpleOrderHome:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5